apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: labsessions.dozlab.io
spec:
  group: dozlab.io
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            required:
            - userId
            - sessionId
            properties:
              userId:
                type: string
                description: "ID of the user requesting the lab session"
              sessionId:
                type: string
                description: "Unique identifier for this lab session"
              resources:
                type: object
                properties:
                  memory:
                    type: string
                    default: "4Gi"
                  cpu:
                    type: string
                    default: "2"
                  storage:
                    type: string
                    default: "10Gi"
              config:
                type: object
                properties:
                  vsCodePassword:
                    type: string
                  enableTerminal:
                    type: boolean
                    default: true
                  enableVSCode:
                    type: boolean
                    default: true
                  enableSSH:
                    type: boolean
                    default: true
              timeout:
                type: string
                default: "2h"
                description: "Session timeout duration"
          status:
            type: object
            properties:
              phase:
                type: string
                enum:
                - "Pending"
                - "Creating"
                - "Running"
                - "Failed"
                - "Terminating"
                - "Terminated"
                default: "Pending"
              message:
                type: string
                description: "Human readable message about current status"
              podName:
                type: string
                description: "Name of the created pod"
              serviceName:
                type: string
                description: "Name of the created service"
              endpoints:
                type: object
                properties:
                  vscode:
                    type: string
                  terminal:
                    type: string
                  ssh:
                    type: string
              vmIP:
                type: string
                description: "IP address assigned to the VM"
              podIP:
                type: string
                description: "IP address of the pod"
              createdAt:
                type: string
                format: date-time
              expiresAt:
                type: string
                format: date-time
              conditions:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                    status:
                      type: string
                      enum:
                      - "True"
                      - "False"
                      - "Unknown"
                    lastTransitionTime:
                      type: string
                      format: date-time
                    reason:
                      type: string
                    message:
                      type: string
    subresources:
      status: {}
    additionalPrinterColumns:
    - name: Phase
      type: string
      jsonPath: .status.phase
    - name: User
      type: string
      jsonPath: .spec.userId
    - name: Pod
      type: string
      jsonPath: .status.podName
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
  scope: Namespaced
  names:
    plural: labsessions
    singular: labsession
    kind: LabSession
    shortNames:
    - ls