---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lab-session-example
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: charts/dozlab-session
      sourceRef:
        kind: GitRepository
        name: dozlab-infra
        namespace: flux-system
      interval: 1m

  # Automatic upgrades when chart changes
  upgrade:
    remediation:
      retries: 3

  # Helm values for this session
  values:
    # Session configuration
    session:
      id: "example-session-123"
      userId: "user-456"

    # Additional labels for resource tracking
    labels:
      team: "platform"
      environment: "development"

    # Rootfs configuration
    # ⚠️  Ensure the rootfs image includes:
    # - Docker daemon on tcp://0.0.0.0:2375
    # - SSH server enabled
    # - Required tools and dependencies
    rootfs:
      imageUrl: "https://storage.googleapis.com/your-bucket/dozlab-k8s.ext4"
      diskSize: "4G"

    # Network settings (usually don't need to change)
    network:
      gatewayIp: "172.16.0.1"
      vmIp: "172.16.0.2"
      tapDevice: "tap0"

    # Firecracker VM specifications
    firecracker:
      vm:
        cpuCount: "2"
        memory: "2048"  # 2GB
      resources:
        limits:
          memory: "3Gi"
          cpu: "2000m"
        requests:
          memory: "2Gi"
          cpu: "1000m"

    # VS Code Server configuration
    codeServer:
      # 🔐 SECURITY: Generate a strong password
      # Example: openssl rand -base64 32
      password: "REPLACE-WITH-SECURE-PASSWORD"
      # Allow editing files in workspace
      workspaceReadOnly: false

    # Service configuration
    service:
      type: ClusterIP  # Change to LoadBalancer or NodePort if needed
      ports:
        vscode: 8080
        terminal: 8081
        ssh: 22

    # Volume sizes (ephemeral storage)
    volumes:
      kernels:
        sizeLimit: "3Gi"
      vmData:
        sizeLimit: "10Gi"
      vscodeData:
        sizeLimit: "2Gi"

  # Post-deployment verification
  test:
    enable: false

  # Timeout for operations
  timeout: 10m
